[package]
name = "masterstat"
description = "Get server addresses from QuakeWorld master servers."
keywords = ["masters", "quake", "quakeworld", "servers"]
repository = "https://github.com/vikpe/masterstat-rust"
authors = ["Viktor Persson <viktor.persson@arcsin.se>"]
version = "0.2.0"
edition = "2021"
license = "MIT"
include = [
    "/Cargo.toml",
    "/LICENSE",
    "/README.md",
    "/src/**",
    "/tests/**",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.82"
binrw = "0.14.1"
futures = "0.3.30"
tinyudp = "0.4.0"
tokio = { version = "1.37.0", features = ["rt", "sync"] }

[dev-dependencies]
pretty_assertions = "1.4.0"
